# Copyright Aberic Person. All Rights Reserved.
#
# Is licensed under the: GNU General Public License v2.0
#

version: '2'

services:

  db:
    container_name: db
    image: mariadb
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: fns
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  edge:
    container_name: edge
    image: aberic/fabric-edge
    environment:
      # 初始化超级管理员账号密码
      - USERNAME=admin
      - PASSWORD=password
      # 日志打印级别
      - LOG_LEVEL=error
      # MySQL数据库连接信息
      - MYSQL_DATA_SOURCE_URL=jdbc:mysql://db:3306/fns?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      - MYSQL_DATA_SOURCE_USERNAME=root
      - MYSQL_DATA_SOURCE_PASSWORD=admin123
      # - WORKING_DIR=/data
    command: bash /home/fns.sh
    ports:
      - 8080:8080